### ISSUE TITLE
Make 'dependencies' 'devdependencies'

### ISSUE THREAD

**Issue by thebuilder** [gaikai/ngTestHarness#11]
Installing the package downloads Karma and JSDoc which shouldn't be required.

**Comment by dhanashree89** [comment]
Thank you for your response. We will get back to you asap.

**Comment by Lastalas** [comment]
This shouldn't be a problem.  We'll update the library this week.  We appreciate the feedback.

**Comment by Lastalas** [comment]
Took waaaayyy too long.  My apologies.  The change has been made.
